version: "3"
services:
  mysql:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - "default-authentication-plugin=mysql_native_password"
    volumes:
      - ./mysql:/var/lib/mysql
